### ISSUE TITLE
JiKeScrollView.m 87行

### ISSUE THREAD

**Issue by xuzhenhao** [lilongcnc/JiKeScrollView#1]
当data.count > 3时，会数组越界。第一组数据初始化的方式不是很友好，因为我可能就想一组数据源一直循环，而不是多次给。

**Comment by lilongcnc** [comment]
?

**Comment by xuzhenhao** [comment]
其实就是第一组数据的初始化必须按你的demo中的来，不能多设和少设。view固定是3个的，但循环时，是按数组的count的

**Comment by lilongcnc** [comment]
时间有点久了,我自己都忘了怎么初始化的了,我回头看下
